
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { database } from '@/lib/database';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Supabase URL and Key must be defined in .env');
}
// Check if we're in offline mode
const isOfflineMode = import.meta.env.VITE_SUPABASE_ANON_KEY === 'offline_mode';

// Use local database client in offline mode, otherwise use Supabase
export const supabase = isOfflineMode
  ? database as any
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
